version: "3.3"
services:
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - $PROJECT_DIR/data/minio:/data
    networks:
      hadoop-cluster:
    command:
      - server
      - /data
      - --console-address
      - ":9001"